### ISSUE TITLE
Upgrading Clojure version

### ISSUE THREAD

**Issue by kephale** [scijava/scripting-clojure#2]
Hello Friendly Scijava Devs,

I'm wondering if it would be possible to upgrade the Clojure version to 1.6, or at least something above 1.3 which has compatibility issues with more recent Clojure versions. I would be happy to take a pass at it if it isn't as simple as changing the version in the pom to 1.6.0, but am not familiar with the build process.

Thank you,
Kyle

**Comment by ctrueden** [comment]
Good idea. Your PR #3 has been merged, which resolves this issue!
